"""create

Revision ID: 303115805c5a
Revises: 
Create Date: 2024-10-22 22:38:46.231873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '303115805c5a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ddos_attacks_time',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('saddr', sa.String(), nullable=True),
    sa.Column('avg_dur', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ddos_attacks_time_id'), 'ddos_attacks_time', ['id'], unique=False)
    op.create_index(op.f('ix_ddos_attacks_time_saddr'), 'ddos_attacks_time', ['saddr'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ddos_attacks_time_saddr'), table_name='ddos_attacks_time')
    op.drop_index(op.f('ix_ddos_attacks_time_id'), table_name='ddos_attacks_time')
    op.drop_table('ddos_attacks_time')
    # ### end Alembic commands ###
